### ISSUE TITLE
[Obsolete] UseJwtBearerAuthentication

### ISSUE THREAD

**Issue by aredfox** [Azure-Samples/active-directory-b2c-dotnetcore-webapi#12]
Please update to dotnetcore 2.0 as this method is now obsolete
`UseJwtBearerAuthentication` in `Startup.cs`

**Comment by gsacavdm** [comment]
This has been address in the [dotnetcore2.0 branch](https://github.com/Azure-Samples/active-directory-b2c-dotnetcore-webapi/tree/dotnetcore2.0)
