### ISSUE TITLE
Referenced branch for dotnetcore2.0 does not exist

### ISSUE THREAD

**Issue by llenroc** [Azure-Samples/active-directory-b2c-dotnetcore-webapi#14]
Within the README.md file, it notes, "For the DotNet Core 2.0 version of this sample, check out the dotnetcore2.0 branch.", but the dotnetcore2.0 branch link that is referenced does not exist.

Please confirm.

**Comment by gsacavdm** [comment]
Master branch is now dotnet core 2.0. There's no more dotnet core 2.0 branch.
I've removed that note from the readme. Apologies for the confusion.
