### ISSUE TITLE
Suggestion - Add a Paragraph to Get Started from Scratch

### ISSUE THREAD

**Issue by laultman** [Azure-Samples/active-directory-b2c-dotnetcore-webapi#16]
It is extremely nice to have an example to look at! It would be great to have a "This is how you start your own NEW project..."
Since this is a AAD B2C example and naturally people must login, which starting template is the right one for a B2C application: No Auth, Individual User, Work/School, and I ruled out Windows Auth?
Just a few comments about rolling your own would be greatly appreciated.
Thanks

**Comment by jmprieur** [comment]
Closing as this sample is being archived in favor of a better sample
