### ISSUE TITLE
Downloaded the sample fresh, ran it in visual studio, got the index page but then can't get token.

### ISSUE THREAD

**Issue by jg11jg** [Azure-Samples/active-directory-b2c-dotnetcore-webapi#17]
https://jwt.ms/#error=redirect_uri_mismatch&error_description=AADB2C90006%3a+The+redirect+URI+%27https%3a%2f%2fjwtinspect.azurewebsites.net%27+provided+in+the+request+is+not+registered+for+the+client+id+%279595a991-a717-4669-9af0-d58420ad733a%27.%0d%0aCorrelation+ID%3a+67dda45e-57ef-46bc-ad0d-9ea7e1b104e3%0d%0aTimestamp%3a+2018-01-18+21%3a25%3a58Z%0d%0a

**Comment by parakhj** [comment]
@jg11jg Fixed it. Thanks for pointing it out. We had updated the app registration to whitelist jwt.ms instead of jwtinspect.azurewebsites.net.

I have updated the code. Let me know if it doesn't work.

**Comment by windperson** [comment]
Hi @parakhj,
Now I run the sample from my local computer, it has another kind of error:

https://jwt.ms/#error=invalid_request&error_description=AADB2C90205%3a+This+application+does+not+have+sufficient+permissions+against+this+web+resource+to+perform+the+operation.%0d%0aCorrelation+ID%3a+da198d6e-88ef-4be0-9259-7955118d9c89%0d%0aTimestamp%3a+2018-08-20+09%3a44%3a38Z%0d%0a

**Comment by tategriffin** [comment]
@parakhj I'm getting the same error as @windperson. I believe the Application with an ID 9595a991-a717-4669-9af0-d58420ad733a defined in the fabrikamb2c tenant needs to be granted API Access to the Application with an ID 25eef6e4-c905-4a07-8eb4-0d08d5df8b3f.

**Comment by AbhishekHumagain** [comment]
> @parakhj I'm getting the same error as @windperson. I believe the Application with an ID 9595a991-a717-4669-9af0-d58420ad733a defined in the fabrikamb2c tenant needs to be granted API Access to the Application with an ID 25eef6e4-c905-4a07-8eb4-0d08d5df8b3f.

getting the same issue. Did you find any solution for this?

**Comment by tategriffin** [comment]
@AbhishekHumagain My solution was to use my own tenant instead of the fabrrikamb2c tenant. I was able to get it working that way after assigning the correct permissions to the correct application IDs. If you go that route, see [my pull request ](https://github.com/Azure-Samples/active-directory-b2c-dotnetcore-webapi/pull/22)for another change to the config. The "client" vs "audience" terminology was misleading.

**Comment by jmprieur** [comment]
Closing as this sample is being archived in favor of a better sample
