### ISSUE TITLE
Sign In Policy allows user to keep logged in - This confuses the menus

### ISSUE THREAD

**Issue by ghost** [Azure-Samples/active-directory-b2c-dotnetcore-webapi#19]
For some reason, the Sign In/Sign up policy doesn't have a checkbox to keep the user logged in.  However, if you switch to a pure Sign In policy, you get the option.  If you select 'Keep me signed in', then the next time you start your Web Application, you are already authenticated (you can prove this by hitting the 'About' menu and you won't be prompted).  So here's the issue: when you are already authenticated and you start the application up, you get the 'Sign In' menu option.  This should be a 'Sign Out' option but the User.Identity.IsAuthenticated property isn't reflecting the current state.  Is there any way to force this property to be correct?  Is there any way to kick the authentication system into gear in code without having to hit the '[Authorize]' attribute first.

**Comment by jmprieur** [comment]
Closing as this sample is being archived in favor of a better sample
