### ISSUE TITLE
Any examples or suggestions using a shared secret for client credentials using b2c?

### ISSUE THREAD

**Issue by ghost** [Azure-Samples/active-directory-b2c-dotnetcore-webapi#20]
I am using your [example](https://github.com/Azure-Samples/active-directory-b2c-dotnetcore-webapi) and I am trying to pass a shared secret. I could not make it work even following the documentation found on [Azure Active Directory v2.0 and the OAuth 2.0 client credentials flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-protocols-oauth-client-creds)

I am getting the following error:
`{
    "error": "invalid_resource",
    "error_description": "AADSTS50001: The application named https://adanasoft.onmicrosoft.com was not found in the tenant named adanasoft.onmicrosoft.com.  This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant.  You might have sent your authentication request to the wrong tenant.\r\nTrace ID: b1bf7f81-92ad-44c0-8d6e-968bff6c0600\r\nCorrelation ID: 6cf6cf64-67f2-4f43-b03f-6309e252cf85\r\nTimestamp: 2018-07-13 03:14:52Z",
    "error_codes": [
        50001
    ],
    "timestamp": "2018-07-13 03:14:52Z",
    "trace_id": "b1bf7f81-92ad-44c0-8d6e-968bff6c0600",
    "correlation_id": "6cf6cf64-67f2-4f43-b03f-6309e252cf85"
}`

I ensured that my tenant exists. Do you have any recommendations or any tutorials that implement this approach?

Thanks for the tutorial!

**Comment by jmprieur** [comment]
Closing as this sample is being archived in favor of a better sample
