### ISSUE TITLE
secure a web application and a webapi using b2C and dotnetcore : 404 - File or directory not found

### ISSUE THREAD

**Issue by doorwaaar** [Azure-Samples/active-directory-b2c-dotnetcore-webapi#21]
Hi ,  I have some issues when using azure ad b2C  .

the error message is :  404 - File or directory not found.
the error occur when getting access token
I have to secure a web application and a webapi using b2C using dotnetcore, both are registered on azure ad
the code sample is here : https://github.com/doorwaaar/ad_auth-b2c-webapi-webmvc
Someone can help me fine whats wrong  ?
Do you have some links to secure a web application and a webapi using b2C and  dotnetcore ?

![1](https://user-images.githubusercontent.com/44276722/48089971-fcdf3300-e205-11e8-80bc-cc7bfe013de2.png)
![2](https://user-images.githubusercontent.com/44276722/48089973-fd77c980-e205-11e8-872d-4ab57cc74be5.png)
![3](https://user-images.githubusercontent.com/44276722/48089974-fd77c980-e205-11e8-8101-74c1139bb996.png)
![4](https://user-images.githubusercontent.com/44276722/48089975-fd77c980-e205-11e8-8614-333e56090777.png)
![5](https://user-images.githubusercontent.com/44276722/48089976-fe106000-e205-11e8-9432-de8eaefb5150.png)

**Comment by jmprieur** [comment]
Closing as this sample is being archived in favor of a better sample
