### ISSUE TITLE
This sample is outdated

### ISSUE THREAD

**Issue by iamalexmang** [Azure-Samples/active-directory-b2c-dotnetcore-webapi#24]
IMHO, this sample should be urgently updated to use MSAL and the latest endpoint version. Also, having parity in the way AAD B2C is configured in other samples (by using an AzureADB2C section in the appconfig.json file would improve the quality a lot.

**Comment by iamalexmang** [comment]
@jennyf19, wanted to bring this one to your attention as well.
I believe this is the missing link towards having a complete end-to-end (web app + web api) dotnetcore based set of samples.

**Comment by jennyf19** [comment]
Thanks @amang2205 -> will bring this up w/the team.

**Comment by danlopez** [comment]
Hey @jennyf19 - This is't up to date, is it? I'm trying to find a relevant example that uses the [`AddAzureADBearer`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.azureadauthenticationbuilderextensions.addazureadbearer?view=aspnetcore-3.0) method and this is all that I'm finding...

**Comment by jennyf19** [comment]
@danlopez have you see this newer [Web app calling Web API with b2c sample](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/4-WebApp-your-API/4-2-B2C)...will this work for you? 
cc: @jmprieur

**Comment by danlopez** [comment]
Thanks @jennyf19! So, just to clarify - is the `AddAzureADBearer` method not the suggested approach, and instead we should be using `AddProtectedWebApi`? Second, when is Microsoft.Identity.Web going to be released (outside of a preview version)? Alternatively - are you recommending using the preview version of this for production apps?

**Comment by jmprieur** [comment]
@danlopez : AddProtectedWebApi is the recommended future, indeed. The ASP.NET Core Web app and Web API templates will progressively use Microsoft.Identity.Web (see https://github.com/AzureAD/microsoft-identity-web/wiki/web-api-template). The release of Microsoft.Identity.Web GA will be quality based; when we are confident that the public API won't drastically change and users tell us it's good we can release, we'll GA.

Some customers already adopted Microsoft.Identity.Web in production ... I would not say that we recommend the preview as we don't commit to not change things. But we are committed to supporting the product.

**Comment by jmprieur** [comment]
Closing as this sample is being archived in favor of a better sample
