### ISSUE TITLE
AADB2C90205: This application does not have sufficient permissions against this web resource to perform the operation

### ISSUE THREAD

**Issue by AndrewDGrant** [Azure-Samples/active-directory-b2c-dotnetcore-webapi#27]
I am getting the above error after following the optional directions in the README.md file to add my own tenancy. 

Also, the user does appear to be getting created even though I cannot see them in the user list of the B2C console. I can log in again with the same password and I cannot recreate the user again with the same name. However, I cannot see the user or delete the user which I need to do to test this software.

**Comment by jmprieur** [comment]
@AndrewDGrant : did you request permission to the Web API?
Did you see https://github.com/AzureAD/microsoft-identity-web/wiki/Web-APIs#case-of-a-b2c-web-api ? and https://github.com/AzureAD/microsoft-identity-web/tree/master/tests/B2CWebAppCallsWebApi ?

**Comment by AndrewDGrant** [comment]
I am using the code in this example. Shouldn't it already be requesting any needed permissions and if I need to do anything shouldn't the instructions be in the README.md file?

**Comment by jmprieur** [comment]
Closing as this sample is being archived in favor of a better sample
