### ISSUE TITLE
Client ID

### ISSUE THREAD

**Issue by spottedmahn** [Azure-Samples/active-directory-b2c-dotnetcore-webapi#3]
In '[Step 5: Configure the sample with your app coordinates](https://github.com/Azure-Samples/active-directory-b2c-dotnetcore-webapi)' it says 

> Find the assignment for ClientID and replace the value with the Application ID from Step 2

but in step 2 you create the tenant.  It would seem this should be the app id from creating the web app or web api in the tenant.  Please advise.  Thanks!

**Comment by parakhj** [comment]
Fixed the README to say step 4.
