### ISSUE TITLE
Audience Validation Failed

### ISSUE THREAD

**Issue by spottedmahn** [Azure-Samples/active-directory-b2c-dotnetcore-webapi#4]
I'm trying to follow the demo [here ](https://github.com/Azure-Samples/active-directory-b2c-dotnetcore-webapi) but I must have doing something wrong.  I'm receiving:

> Audience validation failed. Audiences: '25eef6e4-c905-4a07-8eb4-0d08d5df8b3f'. Did not match: validationParameters.ValidAudience: '49789056-09c1-4ad1-8038-b0235472f36e' or validationParameters.ValidAudiences: 'null'.

## Azure Config
![image](https://user-images.githubusercontent.com/14079228/27808259-a00e3c44-6014-11e7-97e8-e1f2e6bf97b1.png)

## WebApi Changes
![image](https://user-images.githubusercontent.com/14079228/27808211-5dc7a564-6014-11e7-8787-52039c2e8d4b.png)

## JWT Token
![image](https://user-images.githubusercontent.com/14079228/27808329-14293ae8-6015-11e7-8eca-9808fc974dd5.png)

I see that the **aud** value in the token above is the same as the error above.  Please advise.  Thanks!

**Comment by parakhj** [comment]
What you are looking at is an access token, which is intended for the specific API that you defined in your scope. If you look at your outgoing call (using something like fiddler), you'll likely notice the scope parameter is https://someb2ctenant.onmicrosoft.com/APIidentifier/demo.read. The token is intended for the app that is registered as https://someb2ctenant.onmicrosoft.com/APIidentifier

**Comment by spottedmahn** [comment]
Hi @parakhj thanks for the response.  I've tried using Fiddler to capture the traffic but I'm not seeing it.  I'm using the GitBash command shell to execute curl perhaps that's why?

![image](https://user-images.githubusercontent.com/14079228/27929815-751e97d6-6262-11e7-944f-276c52988665.png)

Here's the scope's I've defined in my Web API app:

![image](https://user-images.githubusercontent.com/14079228/27917358-c7393ffe-6239-11e7-8b7d-df005606ed60.png)

Shouldn't https://spottedmahnb2c.onmicrosoft.com/b2c-test-1/demo.read be a valid URL?

I'm still unclear on what I'm doing wrong.  Thanks for your help!

**Comment by parakhj** [comment]
No it's not meant to be a valid URL. It's just a value that is formatted in the form of a URL (to ensure the whole string is unique). 

You should get the fiddler when you are obtaining the token, not when you are sending it to the API. I'm curious how you ended up obtaining a token with that 'aud' value.

If your API (as identified by https://spottedmahnb2c.onmicrosoft.com/b2c-test-1) has the application ID '49789056-09c1-4ad1-8038-b0235472f36e', the 'aud' should be that application ID.

**Comment by spottedmahn** [comment]
> No it's not meant to be a valid URL. It's just a value that is formatted in the form of a URL (to ensure the whole string is unique).
I see, thanks for clarifying.

Do I need to change something in `Views\Home\Index.cshtml`?  When I click 'Obtain a token by signing in here. ' I'm logging into the fabrikamb2c tenant and not mine like I would have suspected.

Does this help?
![image](https://user-images.githubusercontent.com/14079228/27932440-c1769580-626b-11e7-92f5-cc506c9c9038.png)

I can save the Fiddler session and upload if that helps? @parakhj

**Comment by parakhj** [comment]
Oh i see. You're getting an access token for an application registered in the fabrikamb2c tenant.

Could you double check the changes you have made in appsettings.json? Perhaps your configuration settings didn't get saved?

**Comment by spottedmahn** [comment]
Hi @parakhj I've double checked and the values are correct in appsettings.json

![image](https://user-images.githubusercontent.com/14079228/28173612-f66124da-67bc-11e7-8f08-8d6ac9a10dc2.png)

I think the problem has to do with `Views\Home\Index.html`

```<a href="https://login.microsoftonline.com/fabrikamb2c.onmicrosoft.com/oauth2/v2.0/authorize?p=B2C_1_SUSI&client_id=9595a991-a717-4669-9af0-d58420ad733a&nonce=defaultNonce&redirect_uri=https%3A%2F%2Fjwtinspect.azurewebsites.net&scope=https%3A%2F%2Ffabrikamb2c.onmicrosoft.com%2Fdemoapi%2Fdemo.read&response_type=token&prompt=login" target="_blank">here.</a>```

**Comment by parakhj** [comment]
Sorry I haven't worked with this sample much - but from a quick glace at the code, i think you're right. That link seems to be hardcoded in there. I'll add a task to our backlog to make the fix, but could you try updating the link in index.html and trying it out?

**Comment by spottedmahn** [comment]
Np @parakhj 

I got it **working**!

1. Change the tenant in the url
1. Change the policy in the url
1. Change the client id to be the client id of my web app
1. Change the scope string to my scope path/uri
1. Add https://jwtinspect.azurewebsites.net to my web app redirect/reply urls

```<a href="https://login.microsoftonline.com/spottedmahnb2c.onmicrosoft.com/oauth2/v2.0/authorize?p=B2C_1_Sign-Up_or_Sign-In&client_id=d0a1dacb-a76f-4cd3-8055-d387a7d821ca&nonce=defaultNonce&redirect_uri=https%3A%2F%2Fjwtinspect.azurewebsites.net&scope=https%3A%2F%2Fspottedmahnb2c.onmicrosoft.com%2Fdemoapi%2Fdemo.read&response_type=token&prompt=login" target="_blank">here.</a>```

So it would seem, you can't customize this demo for your tenant w/o a web app.
