### ISSUE TITLE
ASP.NET Core 2.0

### ISSUE THREAD

**Issue by fugaku** [Azure-Samples/active-directory-b2c-dotnetcore-webapi#7]
Is this updated to ASP.NET Core 2.0 ?

**Comment by markwest51** [comment]
this works in .Net Core 2.0, just needed to add these 2 lines in the Startup.cs, ConfigureServices method

services.AddAuthentication(options =>
            {
                options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
            })

I added a swagger configuration so i could see that the controller/method was in fact being blocked by unauthorized method -> now for the next part doing React app to talk to B2C to send the token down

**Comment by gsacavdm** [comment]
There's a branch in this sample for [dotnetcore 2.0](https://github.com/Azure-Samples/active-directory-b2c-dotnetcore-webapi/tree/dotnetcore2.0)
