### ISSUE TITLE
IDX10500: Signature validation failed. No security keys were provided to validate the signature

### ISSUE THREAD

**Issue by firewave-remo** [Azure-Samples/active-directory-b2c-dotnetcore-webapi#9]
I have tried the 2.0 example.

First i had to add a default AuthenticateScheme. I had an error telling me that there is no default scheme. So i have added `JwtBearerDefaults.AuthenticationScheme` to the `services.AddAuthentication` method.

In my second try i get this error in the output log and a 401 on the client side:
```
Failed to validate the token [MyTokenHere]
Microsoft.IdentityModel.Tokens.SecurityTokenInvalidSignatureException: IDX10500: Signature validation failed. No security keys were provided to validate the signature.
at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.<HandleAuthenticateAsync>d__6.MoveNext()
```

What am i missing?

**Comment by Ripper555** [comment]
I'm having the same problem but with some weird behavior. When I first tried the 2.0 example with my own b2c info it worked. I tried to match my api with the example setup and had the error on Authentication: 

`Bearer error="invalid_token", error_description="The signature is invalid"`

Went back to this example and gave me 500 error AuthenticationScheme as above and then started giving me the same invalid signature error as my own api had. I don't know what changed where because it seemed that nothing changed. My only guess is a bug somewhere in the process.

Also If I paste my token into: https://jwt.io/
It says "Invalid Signature". Does anyone know where to post this potential issue?

**Comment by firewave-remo** [comment]
for the jwt.io "error" see here: https://stackoverflow.com/questions/44330242/azure-ad-b2c-token-validation-does-not-work?rq=1

jwt.io is not able to read it correctly.

**Comment by Ripper555** [comment]
@VSDekar Thanks. That answers that. 

Please let me know if you find a fix for the API. I have based my Xamarin Forms applications off B2C and now I'm stuck on this problem not being able to communicate with my API.

**Comment by Ripper555** [comment]
@VSDekar 
So I was answered on the other thread:

In Startup.cs (ConfigureServices method)
`services.AddAuthentication(options => 
{ 
options.DefaultScheme = JwtBearerDefaults.AuthenticationScheme; 
}) 
.AddJwtBearer(options => { options.Authority = string.Format("https://login.microsoftonline.com/tfp/{0}/{1}/v2.0/", Portable.Constants.Constants.Tenant, Portable.Constants.Constants.PolicySignUpSignIn); options.Audience = Portable.Constants.Constants.ClientID; options.RequireHttpsMetadata = false; options.Events = new JwtBearerEvents { OnAuthenticationFailed = AuthenticationFailed }; });`

In Configure method (before app.UseMvc();):
`app.UseAuthentication();`

The example doesn't have app.UseAuthentication(); That might be it. I have it working now.

**Comment by firewave-remo** [comment]
@Ripper555 
I got it working now. Your pull request brought me on the right track.

We have to use the options object already provided in `AddJwtBearer` and not create a `new JwtBearerOptions` object.

Bad:
```csharp
.AddJwtBearer(option => new JwtBearerOptions // <--- Evil 
                {
                    Authority = string.Format("https://login.microsoftonline.com/tfp/{0}/{1}/v2.0/",
                    Configuration["Authentication:AzureAd:Tenant"], Configuration["Authentication:AzureAd:Policy"]),
                    Audience = Configuration["Authentication:AzureAd:ClientId"],
                    Events = new JwtBearerEvents
                    {
                        OnAuthenticationFailed = AuthenticationFailed
                    },
                });
```

Good:
```csharp
.AddJwtBearer(options => {
                    options.Authority = string.Format("https://login.microsoftonline.com/tfp/{0}/{1}/v2.0/", Configuration["Authentication:AzureAd:Tenant"], Configuration["Authentication:AzureAd:Policy"]);
                    options.Audience = Configuration["Authentication:AzureAd:ClientId"];
                    options.Events = new JwtBearerEvents {
                        OnAuthenticationFailed = AuthenticationFailed
                    };
                });
````
